# 此工作流将部署构建好的 h5 应用到阿里云 OSS
# 仅在成功构建后由 build 工作流触发执行

name: 部署 myy-app 生产版本到阿里云 OSS

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'apps/myy-app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aly-deploy-test
    steps:
    - uses: actions/checkout@v4
    
    - name: 安装 pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        run_install: false

    - name: 使用 Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    # 构建项目（因为工作流间无法共享artifacts，所以需要重新构建）
    - name: 安装依赖
      run: pnpm install
    
    - name: 构建项目
      env:
        NODE_ENV: production
        TARO_APP_BUILD_ENV: production
        TARO_APP_AI_API_KEY: ${{ secrets.TARO_APP_AI_API_KEY }}
        TARO_APP_AI_API_BASE_URL: ${{ vars.TARO_APP_AI_API_BASE_URL }}
        TARO_APP_API_BASE_URL: ${{ vars.TARO_APP_API_BASE_URL }}
      run: pnpm --filter myy-app run build:h5
    
    # 安装 tsx 运行时依赖
    - name: 安装 tsx
      run: pnpm install tsx @types/node ali-oss @types/ali-oss
      working-directory: ./apps/myy-app

    # 上传到阿里云 OSS
    - name: 上传到阿里云 OSS
      env:
        ALIBABA_CLOUD_ACCESS_KEY_ID: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID }}
        ALIBABA_CLOUD_ACCESS_KEY_SECRET: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET }}
        PAGE_OSS_BUCKET: ${{ vars.PAGE_OSS_BUCKET }}
        PAGE_OSS_REGION: ${{ vars.PAGE_OSS_REGION }}
        PAGE_OSS_PATH: ${{ vars.PAGE_OSS_PATH }}
      run: |
        cd apps/myy-app
        npx tsx upload.ts
